# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Cling variables
cling_env_name: "cling-{{ cling_version }}"

# Julia variables
julia_bin_url: "https://julialang-s3.julialang.org/bin/linux/x64/{{ julia_version[:3] }}/julia-{{ julia_version }}-linux-x86_64.tar.gz"
julia_bin_checksum: "sha256:b8fe23ee547254a2fe14be587284ed77c78c06c2d8e9aad5febce0d21cab8e2c"

# R variables
r_deps:
  - "libxml2-devel"
  - "openssl-devel"