# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Install nginx web server and install certificates

- name: make sure /etc/nginx/ssl exists
  file:
    path: "{{ remote_path_nginx_proxy_ssl }}/"
    state: "{{ item }}"
    owner: "{{ ssl_certs_owner }}"
    group: "{{ ssl_certs_owner }}"
    mode: 0700
  become: true
  with_items:
    - directory
    - touch

- name: install SSL key
  copy:
    src: "{{ local_path_nginx_proxy_ssl }}/{{ ssl_key_name_nginx_proxy }}"
    dest: "{{ remote_path_nginx_proxy_ssl }}/{{ ssl_key_name_nginx_proxy }}"
    owner: "{{ ssl_certs_owner }}"
    group: "{{ ssl_certs_owner }}"
    mode: 0600
  become: true

- name: install SSL certificate
  copy:
    src: "{{ local_path_nginx_proxy_ssl }}/{{ ssl_cert_name_nginx_proxy }}"
    dest: "{{ remote_path_nginx_proxy_ssl }}/{{ ssl_cert_name_nginx_proxy }}"
    owner: "{{ ssl_certs_owner }}"
    group: "{{ ssl_certs_owner }}"
    mode: 0600
  become: true
  
- name: install Diffie-Hellman key
  copy:
    src: "{{ local_path_encryption_data }}/{{ ssl_dhparam_name_nginx_proxy }}"
    dest: "{{ remote_path_nginx_proxy_ssl }}/{{ ssl_dhparam_name_nginx_proxy }}"
    owner: "{{ ssl_certs_owner }}"
    group: "{{ ssl_certs_owner }}"
    mode: 0600
  become: true
  
- name: make sure /etc/ssl/ca exists
  file:
    path: "{{ remote_path_ca_cert_ssl }}/"
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  become: true
  with_items:
    - directory
    - touch
  when: self_signed_certs
  
- name: install SSL CA certificate
  copy:
    src: "{{ local_path_nginx_proxy_ssl }}-ca/{{ ssl_cert_name_nginx_proxy.split('.')[0] }}-ca.crt"
    dest: "{{ remote_path_ca_cert_ssl }}/{{ ssl_cert_name_nginx_proxy.split('.')[0] }}-ca.crt"
    owner: "{{ nginx_service_user }}"
    group: "{{ nginx_service_user }}"
    mode: 0644
  become: true
  when: self_signed_certs
