# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Install nginx web server and install certificates

- name: install system nginx
  yum:
    name: nginx
    state: present
  become: true

- name: make sure /etc/nginx/ssl exists
  file:
    path: "{{ ssl_path }}/"
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0700
  become: true
  with_items:
    - directory
    - touch

- name: check if SSL key exists
  stat:
    path: "{{ role_path }}/../../security/ssl.key"
  delegate_to: localhost
  register: key_path

- name: fail when key file does not exist
  fail:
   msg: ssl.key cannot be found.
  when: key_path.stat.exists == false

- name: check if SSL cert exists
  stat:
    path: "{{ role_path }}/../../security/ssl.crt"
  delegate_to: localhost
  register: cert_path

- name: fail when cert file does not exist
  fail:
   msg: ssl.cert cannot be found.
  when: cert_path.stat.exists == false

- name: install SSL key
  copy:
    src: "{{ role_path }}/../../security/ssl.key"
    dest: "{{ ssl_key_path }}"
    owner: root
    group: root
    mode: 0600
  become: true

- name: install SSL certificate
  copy:
    src: "{{ role_path }}/../../security/ssl.crt"
    dest: "{{ ssl_cert_path }}"
    owner: root
    group: root
    mode: 0600
  become: true
  
- name: grant jupyter and nginx service users to read key and cert files
  ansible.posix.acl:
    path: "{{ item[0] }}"
    entity: "{{ item[1] }}"
    etype: "{{ item[2] }}"
    permissions: r
    state: present
  with_nested:
    - [ "{{ ssl_key_path }}", "{{ ssl_cert_path }}" ]
    - [ "{{ jupyterhub_service_user }}", "{{ nginx_service_user }}" ]
    - [ "user", "group" ]

- name: find notebook static directory
  shell: 
    cmd: 'import notebook; import os; print(os.path.join(notebook.__path__[0], "static"));'
    executable: "{{ conda_env_bin_dir }}/python3"
  register: notebook_static_directory

- name: install nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  notify:
    - reload nginx
    - restart nginx

# - name: start the nginx service
#   service: name=nginx state=started enabled=yes
#   become: true
#
# - name: reload nginx
#   service: name=nginx state=reloaded
#   become: true
