# Copyright 2025 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# ---------------------------------------------------
# JupyterHub configuration
# ---------------------------------------------------

# Core jupyterhub components
jupyterhub_pkgs:
  - "python=3.12.0"
  - "jupyterhub=5.3.0"
  - "jupyterlab=4.4.7"

# Additional dependencies
jupyterhub_deps:
  - "batchspawner==1.3.0"
  - "psycopg2-binary==2.9.9"

# List of jupyterlab extensions that will be installed from pip
jupyterlab_extensions:
  - "jupyter-server-proxy==4.4.0"
  - "jupyterlab-git==0.51.1"
  - "jupyter-resource-usage==1.1.1"
  - "jupyter_power_usage==1.2.1"
  - "jupyterlab-lsp==5.1.0"
  - "jupyterlab_latex==4.3.0"
  # - "jupyterlab_h5web==12.3.0"
  # - "jupyter_bokeh==4.0.5"
  # - "jupyterlab-gitlab==4.0.0"
  # - "plotly==6.0.0"
  # - "voila==0.5.8"
  # - "streamlit==1.42.0"
  # - "dash==2.18.2"
  # - "dask-labextension==7.0.0"
  # - "sidecar==0.7.0"

# All the packages related to jupyterhub deployment will be installed
# within an conda environment. This variable controls where we want to
# install this environment. By default conda tends to install the
# environment at <conda_prefix>/envs/<myenv>. This might not be a suitable
# location for some deployments where the admins would want this environment
# on shared file system. We can use this variable to set the location of
# environment
jupyter_env_prefix: "/opt/jupyter"

# Name of the jupyterhub conda environment
jupyter_env_name: "jupyterhub"

# Name of the user under which JupyterHub will be running. This user will be
# added to sudoers group but the user will be allowed to use sudo for only
# spawning the servers using batch spawner. By default this user will not have
# login shell and home directory.
#
# If PAMAuthenticator is used, this user must be `root` to be able to authenticate
# different system users.
jupyterhub_system_user: "root"

# JupyterHub authenticator class
jupyterhub_authenticator_class: "jupyterhub.auth.PAMAuthenticator"

# JupyterHub spawner class
# Currently only LocalProcessSpawner and SlurmSpawner are supported out of the box.
# If any other spawners are used, use `jupyterhub_extra_config` to configure necessary
# config for that spawner.
jupyterhub_spawner_class: "batchspawner.SlurmSpawner"

# JupyterHub Hub IP. This must be an internal IP address that is accessible from
# all other compute hosts in the cluster. If not provided, IP address in
# `ansible_all_ipv4_addresses[0]` will be used.
jupyterhub_hub_ip: ""

# Enable internal TLS for JupyterHub
jupyterhub_internal_tls: true

# Directory where internal certificates are stored
jupyterhub_internal_certs_dir: "{{ jupyterhub_srv_dir }}/internal-ssl"

# List of node names that should be added to self signed TLS certificates. This
# can be list of names or a wild card of the FQDN.
jupyterhub_trusted_alt_names: []
# JupyterHub extra config. This will be added at the end
# of the JupyterHub config which overrides any default values
# used.
#
# If there are any new roles added in this config, they must be
# appended to c.JupyterHub.load_roles instead of overriding
# existing roles.
#
# Available template variables:
# - `jupyterhub_env_prefix`: Conda environment prefix where JupyterHub will be installed
# - `jupyterhub_env_bin_path`: Path to `bin` for the conda environment
jupyterhub_extra_config: ""

# Jupyter server extra config. This will be added at the end
# of the jupyter_server_config.py which overrides any default values
# used.
#
# Available template variables:
# - `jupyterhub_env_prefix`: Conda environment prefix where JupyterHub will be installed
# - `jupyterhub_env_bin_path`: Path to `bin` for the conda environment
jupyter_server_extra_config: ""

# This is the directory where we store the HTML templates, internal certs
# created by jupyterhub for SSL. It should be writable by jupyterhub_service_user
jupyterhub_srv_dir: "/srv/jupyterhub"

# Type of database used for jupyterhub. By default jupyterhub
# uses sqllite3. But for production deployments, they advise to
# use PostgresSql. If set to true PostgreSQL database will be used
# else sqllite3 will be used
#
use_postgresql_db: true

# Set name of database if PostgresSql database is used for jupyterhub.
jupyterhub_db_name: "jupyterhub"

# Directory where jupyterhub logs are redirected
jupyterhub_log_dir: "/var/log/jupyterhub"

# List of admin users for jupyterhub
jupyterhub_admin_users: []
