# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Setup R kernel

- name: install R dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: true
  tags: "r_kernel"
  with_items:
    - "{{ r_deps }}"

- name: setup conda environment for R
  conda:
    name: python
    version: "{{ conda_env_py_version }}"
    environment: "{{ rlang_pkg_path }}"
    state: present
    executable: "{{ conda_prefix }}/bin/conda"
  become: true
  tags: "r_kernel"
  
- name: install R packages in R environment
  conda:
    name: "{{ item }}"
    environment: "{{ rlang_pkg_path }}"
    state: present
    executable: "{{ conda_prefix }}/bin/conda"
  become: true
  tags: "r_kernel"
  with_items:
    - "{{ r_packages }}"

- name: install IRkernel into jupyter
  shell: "source {{ conda_prefix }}/etc/profile.d/conda.sh && conda activate {{ jupyterhub_env_prefix }} && jupyter kernelspec install {{ rlang_pkg_path }}/share/jupyter/kernels/ir --sys-prefix"
  become: true
  register: r_krnl
  changed_when: "'error' not in r_krnl.stderr"
  tags: "r_kernel"

# In the IRkernel json file, R binary is specified without absolute path
# This will be an issue if R is not found on PATH
# So we replace it with absolute path to R using template
- name: make sure R executable has absolute path in irkernel
  template:
    src: kernel.json.j2
    dest: "{{ jupyterhub_env_prefix }}/share/jupyter/kernels/ir/kernel.json"
    mode: 0644
  become: true
  tags: "r_kernel"
    

  