image: docker:20.10.16

variables:
  # When you use the dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

stages:
  - lint
  - test

molecule-test:
  stage: test
  before_script:
    - mkdir -p build/reports
    - apk add --no-cache python3 python3-dev py3-pip gcc git curl build-base autoconf automake py3-cryptography linux-headers musl-dev libffi-dev openssl-dev openssh tar
    - ln -s /usr/bin/python3 /usr/bin/python
    - docker info
    - python3 --version
    - pip install --no-cache-dir -r requirements-dev.txt
    - ansible-galaxy install -r requirements.yml
    - ansible --version
    - molecule --version
    - cp molecule/default/hostfile .
    - cd scripts && ./gen-encrypt-data -c -p -t && cd ..
    - cp .ci/nginx.dhparam.pem encryption/
  script:
    - source encryption/jp-adminrc
    - molecule --debug test
    - cp ansible-lint.xml build/reports/linting.xml
  after_script:
    - sleep 36000
  artifacts:
    paths:
      - build/reports/
    expire_in: 1 day
    
# Create Gitlab CI badges from CI metrics
# This job is allowed to fail so that it will not mark CI as
# failure if this job fails
include:
  - project: 'idris-cnrs/ci-utilities/ci-templates'
    file: 'includes/create-badges.yml'
