---
image: docker:29.6.0

variables:
  # When you use the dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:29.6.0-dind

stages:
  - lint
  - test-rocky
  - test-debian
  - test-ubuntu
  - release

# prepare job YAML anchor
.prepare_step: &prepare_step
  - apk add --no-cache python3 python3-dev py3-pip gcc git curl build-base autoconf automake py3-cryptography linux-headers musl-dev libffi-dev openssl openssl-dev tar bzip2 unzip
  - docker info
  - python3 --version
  - python3 -m venv /root/venv
  - . /root/venv/bin/activate
  - pip install --no-cache-dir --ignore-installed -r requirements-dev.txt
  # If we need to pin Ansible version, do it now
  - if [ ! -z "${ANSIBLE_VERSION}" ]; then pip install "ansible==${ANSIBLE_VERSION}"; fi
  - ansible --version
  - molecule --version
  - mkdir -p admin

# Job template
.job_template:
  variables:
    OS_DIST: "default"
    ANSIBLE_VERSION: ""
  before_script:
    - *prepare_step
  script:
    - molecule --debug test --scenario-name=${OS_DIST}
  after_script:
    - ls -la build
    - ls -la build/reports
  artifacts:
    paths:
      - build/reports/
    expire_in: 1 day
  except:
    - tags

ansible-lint:
  stage: lint
  before_script:
    - mkdir -p build/reports
    - *prepare_step
  script:
    - ansible-lint
  artifacts:
    paths:
      - build/reports/
    expire_in: 1 day
  except:
    - tags

molecule-test-rockylinux9:
  stage: test-rocky
  extends: .job_template

molecule-test-rockylinux10:
  stage: test-rocky
  variables:
    OS_DIST: "rockylinux10"
  extends: .job_template

# # Python 3.14 which is the base container requires Ansible >= 2.20. So stop testing it in CI 
# molecule-test-rockylinux8:
#   stage: test-rocky
#   variables:
#     OS_DIST: "rockylinux8"
#     # For RHEL 8 flavours, last supported Ansible is 2.16/9.13
#     # Ref: https://www.jeffgeerling.com/blog/2024/newer-versions-ansible-dont-work-rhel-8
#     ANSIBLE_VERSION: "9.13.0"
#   extends: .job_template

molecule-test-debian11:
  stage: test-debian
  variables:
    OS_DIST: "debian11"
  extends: .job_template

molecule-test-debian12:
  stage: test-debian
  variables:
    OS_DIST: "debian12"
  extends: .job_template

molecule-test-ubuntu22:
  stage: test-ubuntu
  variables:
    OS_DIST: "ubuntu22"
  extends: .job_template

molecule-test-ubuntu24:
  stage: test-ubuntu
  variables:
    OS_DIST: "ubuntu24"
  extends: .job_template

# Create a new release on GitLab
release:
  stage: release
  before_script:
    - *prepare_step
  script:
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --token "${GALAXY_API_TOKEN}" mahendrapaipuri-ansible_jupyterhub_hpc-*.tar.gz
  only:
    - tags

# Create Gitlab CI badges from CI metrics
# This job is allowed to fail so that it will not mark CI as
# failure if this job fails
include:
  - project: "idris-cnrs/ci-utilities/ci-templates"
    file: "includes/create-badges.yml"
