# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This file contains all the configyuration details of JupyterHub deployment

# Name of the user under which JupyterHub will be running. This user will be
# added to sudoers group
jupyter_usr_name: "jupyter"

# Password for the user defined above. Note that this file will be encrypted
# and we will need vault key to decrpyt the file. So we can store the password
# here safely
jupyter_usr_passwd: "idrisJupyter2022"

# Crypography keys to be used by Jupyerhub env variable JUPYTERHUB_CRYPT_KEY
# These keys are needed to have a persistent auth_state
# Multiple keys may be provided separated by semicolon for key-rotation.
auth_state_crypt_keys: ""

# Installation directory of the conda
conda_install_dir: "/opt/conda"

# JupyterHub version to be installed
jupyterhub_version: "2.1.1"

# Jupyterlab version to be installed
jupyterlab_version: "3.2.9"

# JupyterHub version to be installed
jupyternotebook_version: "6.4.8"
