# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# ---------------------------------------------------
# HPC platform related configuration
# ---------------------------------------------------

# Path to SLURM binaries like sbatch, squeue, scancel
# We run the jupyterhub service as a normal system user without any sudo
# rights by default. However we need to use sudo to change the context for
# submitting jobs as different user. So we need add SLURM commands to list of
# commands that service account can use without password prompt.
# More details can be found here:
# https://jupyterhub.readthedocs.io/en/stable/reference/config-sudo.html
#
# We need to add these binaries to jupyter service user sudoers entry so that
# jupyter service user can spawn jupyter servers on the behalf of the users
# If SLURM commands like sbatch is located at /usr/bin/sbatch we need to
# set this variable as /usr/bin
# Although we can use Ansible find module to get this dynamically it might
# pose few issues depending on platforms.
#
slurm_bin_path: "/usr/bin"

# ---------------------------------------------------
# Conda related configuration
# ---------------------------------------------------
#
# Set this to /opt/conda as we use rpms to install conda 
# and /opt/conda is the default location
#
conda_prefix: "/opt/conda"

# ---------------------------------------------------
# TLS configuration
# ---------------------------------------------------
#
# Use self signed certificates for all services in the
# deployment. Ideal for testing purposes and playbook will
# generate certificates for all hosts. If set to 
# false, playbook expects certificates signed by external CA
# in {{ playbook_dir }}/encryption/{{ inventory_hostname }}
# directory. Key and cert files should be named as 
# {{ inventory_hostname }}.key and {{ inventory_hostname }}.crt
#
self_signed_certs: true

# Local directory on ansible controller machine where self signed
# certificates will be stored
#
local_tls_dir: "{{ playbook_dir }}/admin/tls"

# Local directory on ansible controller machine where generated
# tokens will be stored
#
local_tokens_dir: "{{ playbook_dir }}/admin/tokens"

# Local directory on ansible controller machine where generated
# credentials will be stored
#
local_passwds_dir: "{{ playbook_dir }}/admin/credentials"

# In the case of self signed certificates, we need CA certificate
# bundle for verification. We place all CA certificates here.
# This folder will have relaxed permissions of 0755 so that 
# others can read the certificates. If we are using certificates
# from external CA, this variable will be unused
#
remote_tls_ca_dir: "/etc/ssl/ca"

#
# ---------------------------------------------------
# Monitoring
# ---------------------------------------------------
#
# Bool to set if monitoring stack will be installed
# This will install node exporter, prometheus and grafana stack
# on the host where jupyterhub is installed
# This will also install grafana loki and promtail to monitor
# nginx reverse proxy. In the future support for jupyterhub 
# logs might be added to this stack
# If the user wants to install Prometheus and Grafana on a different
# node it can be configured in the hostfile
install_mon_stack: true

# ---------------------------------------------------
# JupyterHub configuration
# ---------------------------------------------------
#
# Whether to install CDS dashboards in the jupyterhub environment
install_cds_dashboards: true

# core jupyterhub components
jupyterhub_pkgs:
  - "python=3.9.0"
  - "jupyterhub=2.3.0"
  - "jupyterlab=3.2.9"
  - "notebook=6.4.8"

# Additional dependencies
jupyterhub_deps:
  - "batchspawner==1.1"
  - "psycopg2-binary==2.9.3"

# List of jupyterlab extensions that will be installed from pip
jupyterlab_extensions:
  - "jupyterlab-git==0.34.2"
  - "jupyter-resource-usage==0.6.1"
  - "jupyterlab-topbar==0.6.1"
  - "jupyterlab-system-monitor==0.8.0"
  - "jupyterlab_latex==3.1.0"
  - "jupyter_bokeh==3.0.2"
  - "jupyterlab-lsp==3.10.0"
  - "jupyterlab-gitlab==3.0.0"
  - "jupyterlab-quickopen==1.2.0"
  - "ipywidgets==7.6.3"
  - "plotly==5.6.0"
  - "cdsdashboards==0.6.0"
  - "cdsdashboards[user]==0.6.0"
  - "voila==0.3.5"
  - "streamlit==1.7.0"
  - "dash==2.0.0"
  - "dask-labextension==5.2.0"
  - "sidecar==0.5.1"
  - "bokeh==2.4.2"

# All the packages related to jupyterhub deployment will be installed
# within an conda environment. This variable controls where we want to
# install this environment. By default conda tends to install the 
# environment at <conda_prefix>/envs/<myenv>. This might not be a suitable
# location for some deployments where the admins would want this environment
# on shared file system. We can use this variable to set the location of 
# environment
jupyter_env_prefix: "/opt/jupyter"

# Name of the jupyterhub conda environment
jupyter_env_name: "jupyterhub"

# Name of the user under which JupyterHub will be running. This user will be
# added to sudoers group but the user will be allowed to use sudo for only
# spawning the servers using batch spawner. By default this user will not have
# login shell and home directory
jupyterhub_system_group: "jupyter"

# This is the directory where we store the HTML templates, internal certs
# created by jupyterhub for SSL. It should be writable by jupyterhub_service_user
jupyterhub_srv_dir: "/srv/jupyterhub"

# Directory where internal certificates are stored
jupyterhub_internal_certs_dir: "{{ jupyterhub_srv_dir }}/internal-ssl"

# Type of database used for jupyterhub. By default jupyterhub
# uses sqllite3. But for production deployments, they advise to
# use PostgresSql. If set to true PostgreSQL database will be used
# else sqllite3 will be used
#
use_postgresql_db: true

# Set name of database if PostgresSql database is used for jupyterhub.
jupyterhub_db_name: "jupyterhub"

# Directory where jupyterhub logs are redirected
jupyterhub_log_dir: "/var/log/jupyterhub"

# List of admin users for jupyterhub
jupyterhub_admin_users: []

# ---------------------------------------------------
# Nginx configuration
# ---------------------------------------------------

# nginx gets shipped with a systemd service file to
# launch the web server. Usually this systemd file is
# configured to run as root and fork the processes which
# actually run web servers as service users. The master 
# process needs to be root to be able to bind to ports
# less than 1024. Here we run nginx as a normal system user
# and use capabilities to be able to bind the ports less than 
# 1024. Besides we use more restrictive systemd file to have 
# more security. For more details check the systemd service file 
# template in 
# {{ playbood_dir }}/roles/setup_nginx/templates/nginx.service.j2
# file

# HTTPS port that server will listen. By default we use 
# standard 443 port. If the user wants to use non-standard
# port, that can be configured here
nginx_https_port: "443"

# HTTP port that server will listen. By default we use 
# standard 80 port. If the user wants to use non-standard
# port, that can be configured here
nginx_http_port: "80"

# ---------------------------------------------------
# Node exporter configuration
# ---------------------------------------------------

node_exporter_version: "1.1.2"

# Node exporter URL
node_exporter_port: "9100"
node_exporter_address: "{{ inventory_hostname }}"

# ---------------------------------------------------
# Prometheus configuration
# ---------------------------------------------------

# If we are using this playbook to add configuration
# to existing Prometheus installation make sure we set all
# configuration details same as the existing configuration
# The scrape configs for the node exporter and jupyterhub
# will be added to existing scrape configs

# Prometheus related config
prometheus_version: "2.33.0"
prometheus_port: "9090"
prometheus_address: "{{ inventory_hostname }}"
prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "10GB"

# The playbook will make sure that the certificates are in the these
# location for the web config. We also create a password for prometheus
# and set it as a fact.
prometheus_web_config:
  tls_server_config:
    cert_file: "/etc/prometheus/ssl/cert/{{ inventory_hostname }}.crt"
    key_file: "/etc/prometheus/ssl/private/{{ inventory_hostname }}.key"
  basic_auth_users:
     prometheus: "{{ lookup('file', local_passwds_dir + '/prometheus_hashed_passwd') | trim }}"

# ---------------------------------------------------
# Promtail configuration
# ---------------------------------------------------

# Promtail version to install
promtail_version: "2.4.2"

# Promtail server config
# http_listen_port and grpc_listen_port must be integers
promtail_config_server:
  http_listen_address: "{{ inventory_hostname }}"
  http_listen_port: 9080
  grpc_listen_port: 9081
  

# ---------------------------------------------------
# Grafana Loki configuration
# ---------------------------------------------------
  
# Verison of loki to be installed
loki_version: "2.4.1"

# loki server config
loki_config_http_address: "{{ inventory_hostname }}"
loki_config_http_port: "3100"

# local storage where loki data will be stored
loki_config_store: "/var/lib/loki"

# retention period for the index
loki_config_period: "168h"

# Disable authentification
loki_config_auth: false

# ---------------------------------------------------
# Grafana configuration
# ---------------------------------------------------

# Grafana related config
grafana_port: "3000"
grafana_address: "{{ inventory_hostname }}"

# Additional options for grafana "server" section
grafana_server:
  protocol: "https"
  cert_key: "/etc/grafana/ssl/private/{{ inventory_hostname }}.key"
  cert_file: "/etc/grafana/ssl/cert/{{ inventory_hostname }}.crt"

# Grafana admin username and password
grafana_security:
  admin_user: "grafana"
  admin_password: "{{ lookup('file', local_passwds_dir + '/grafana_passwd') | trim }}"
  allow_embedding: true
  
# Directory where JupyterHub dashboard is located
grafana_dashboards_dir: "{{ playbook_dir }}/grafana-dashboards"
