---
# Ansible galaxy requirements for using this playbook

# Roles
roles:
  - name: evandam.conda
    src: https://github.com/evandam/evandam.conda
    version: master
  - name: mambaorg.micromamba
    src: https://github.com/mamba-org/ansible-role-micromamba
    version: v1.2.5
