{
 "title": "JupyterHub Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nb running servers",
   "type": "stat",
   "description": "Current number of running servers",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_running_servers{}" }
   ]
  },
  {
   "title": "Nb active users",
   "type": "stat",
   "description": "Current number of active users",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_total_users{}" }
   ]
  },
  {
   "title": "Avg. Server Spawn Duration",
   "type": "stat",
   "description": "Average time taken for spawning a server. This should be taken too seriously as it includes the time taken by SLURM scheduler to allocate resources.",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jupyterhub_server_spawn_duration_seconds_sum{status=\"success\"}[$__range])) / sum(rate(jupyterhub_server_spawn_duration_seconds_count{status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Avg. Server Stop Duration",
   "type": "stat",
   "description": "Average time taken for spawned servers to stop",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jupyterhub_server_stop_seconds_sum{status=\"success\"}[$__range])) / sum(rate(jupyterhub_server_stop_seconds_count{status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Avg. Proxy Add Duration",
   "type": "stat",
   "description": "Average time taken for adding user routes to proxy",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jupyterhub_proxy_add_duration_seconds_sum{status=\"success\"}[$__range])) / sum(rate(jupyterhub_proxy_add_duration_seconds_count{status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Avg. Proxy Delete Duration",
   "type": "stat",
   "description": "Average time taken for deleting user routes to proxy",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jupyterhub_proxy_delete_duration_seconds_sum{status=\"success\"}[$__range])) / sum(rate(jupyterhub_proxy_delete_duration_seconds_count{status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "JupyterHub Dashboard",
   "type": "text",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "# README \n\nJupyterHub exposes certain metrics in a way that prometheus can understand. More information\non the metrics exposed by JupyterHub can be found at [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/reference/metrics.html) \nofficial documentation.\n\n-  All average metrics presented in the stats are average in the range selected in Grafana main dashboard\n- Nb running servers and Nb active users are current number of running servers and logged in hub users\n- Average server spawn and proxy metrics are the average time taken in the range selected."
   }
  },
  {
   "title": "Avg. Nb of Server Spawns",
   "type": "stat",
   "description": "Average number of server spawns by their status",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_spawn_duration_seconds_count{}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg. Nb Server Stops",
   "type": "stat",
   "description": "Average number of server stops by their status",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_stop_seconds_count{}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Nb HTTP requests by method",
   "type": "stat",
   "description": "Number of HTTP requests by method",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_request_duration_seconds_count{}[$__range])) by (method)",
     "legendFormat": "HTTP method={{method}}"
    }
   ]
  },
  {
   "title": "Nb HTTP requests by code",
   "type": "stat",
   "description": "Number of HTTP requests by response code",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_request_duration_seconds_count{}[$__range])) by (code)",
     "legendFormat": "HTTP code={{code}}"
    }
   ]
  },
  {
   "title": "Hub usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of hub users",
     "type": "timeseries",
     "description": "Time series plot of number of users",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "jupyterhub_total_users{}", "legendFormat": "Total number of users" }
     ]
    },
    {
     "title": "Number of running servers",
     "type": "timeseries",
     "description": "Time series plot of number of running servers",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "jupyterhub_running_servers{}",
       "legendFormat": "Total number of running servers"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Spawn Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Server Spawn Duration",
     "type": "timeseries",
     "description": "Time series plot of average server spawn duration",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_server_spawn_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_server_spawn_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Average Server Poll Duration",
     "type": "timeseries",
     "description": "Time series plot of average server poll duration",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_server_poll_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_server_poll_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Average Server Stop Duration",
     "type": "timeseries",
     "description": "Average time taken to stop the spawned server",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_server_stop_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_server_stop_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Proxy Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Duration for Adding User Routes to Proxy",
     "type": "timeseries",
     "description": "Time series plot of average duration for adding user routes to proxy",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_proxy_add_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_proxy_add_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Average Duration for Polling User Routes from Proxy",
     "type": "timeseries",
     "description": "Time series plot of average duration for polling user routes from proxy",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_proxy_poll_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_proxy_poll_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Average Duration for Deleting User Routes from Proxy",
     "type": "timeseries",
     "description": "Time series plot of average duration for deleting user routes from proxy",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_proxy_delete_duration_seconds_sum{}[$__interval])) by (status) / sum(rate(jupyterhub_proxy_delete_duration_seconds_count{}[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hub HTTP Request Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Duration for HTTP Request by Method",
     "type": "timeseries",
     "description": "Time series plot of average duration for HTTP requests by method",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_request_duration_seconds_sum{}[$__interval])) by (method) / sum(rate(jupyterhub_request_duration_seconds_count{}[$__interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Average Duration for HTTP Request by code",
     "type": "timeseries",
     "description": "Time series plot of average duration for HTTP request by code",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_request_duration_seconds_sum{}[$__interval])) by (code) / sum(rate(jupyterhub_request_duration_seconds_count{}[$__interval])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Average Duration for HTTP Request by handler",
     "type": "timeseries",
     "description": "Time series plot of average duration for HTTP request by handler",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_request_duration_seconds_sum{}[$__interval])) by (handler) / sum(rate(jupyterhub_request_duration_seconds_count{}[$__interval])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hub Startup Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Duration for JupyterHub to startup",
     "type": "timeseries",
     "description": "Time series plot of average duration for jupyterhub to start",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_hub_startup_duration_seconds_sum{}[$__interval])) / sum(rate(jupyterhub_hub_startup_duration_seconds_count{}[$__interval]))",
       "legendFormat": "hub startup"
      }
     ]
    },
    {
     "title": "Average Duration for Spawners to initialise",
     "type": "timeseries",
     "description": "Time series plot of average duration for spawner to initialise",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jupyterhub_init_spawners_duration_seconds_sum{}[$__interval])) / sum(rate(jupyterhub_init_spawners_duration_seconds_count{}[$__interval]))",
       "legendFormat": "spawner init"
      }
     ]
    }
   ]
  }
 ]
}