# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Install grafana loki

- name: create loki system group
  group:
    name: "{{ loki_system_group }}"
    system: true
    state: present
  become: true

- name: create loki system user
  user:
    name: "{{ loki_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ loki_system_group }}"
    createhome: false
  become: true

- name: check if loki is already installed
  stat:
    path: "/usr/local/bin/loki"
  register: get_loki_bin
  become: true

- name: get existing loki version
  shell: "set -o pipefail && /usr/local/bin/loki -version | grep 'loki, version' | awk '{print $3}'"
  args:
   executable: /bin/bash
  register: get_loki_version
  when: get_loki_bin.stat.exists
  # To make this task idempotent
  changed_when: false
  become: true

- name: set loki version variable as fact
  set_fact:
    current_loki_version: "{% if 'stdout' in get_loki_version.keys() %}{{ get_loki_version['stdout'] }}{% else %}\"0.0.0\"{% endif %}"
  become: true

- name: download, unzip and install loki
  block:
    - name: download and install loki release
      get_url:
        url: "{{ loki_download }}"
        dest: "/tmp/{{ loki_archive }}"
        checksum: "sha256:{{ loki_download_github }}/v{{ loki_version }}/SHA256SUMS"
        mode: 0644
      delegate_to: localhost
      register: download_release
      until: download_release is succeeded
      retries: 5
      delay: 2

    - name: unpack loki release
      unarchive:
        src: "/tmp/{{ loki_archive }}"
        dest: "/tmp"
        creates: "/tmp/{{ loki_bin }}"
        mode: 0644
      delegate_to: localhost

    - name: copy loki to /usr/local/bin
      copy:
        src: "/tmp/{{ loki_bin }}"
        dest: "/usr/local/bin/loki"
        mode: 0755
        owner: root
        group: root

    - name: clean-up
      file:
        path: "/tmp/{{ item }}"
        state: absent
      delegate_to: localhost
      loop:
        - "{{ loki_archive }}"
        - "{{ loki_bin }}"
  when: current_loki_version != loki_version
  # Seems like version returned by loki is a git ref and not proper version
  # string. So this task will be executed in idempotent test and so, ignore
  tags:
    - molecule-idempotence-notest

- name: install systemd-unit
  template:
    src: "systemd-loki.j2"
    dest: "/etc/systemd/system/loki.service"
    mode: 0644
  become: true
  notify:
    - reload systemd loki
    - restart systemd loki
