# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: install jupyterhub config file
  template:
    src: jupyterhub_config.py.j2
    dest: "{{ jupyterhub_config_dir }}/jupyterhub_config.py"
    # owner: "{{ jupyterhub_service_user }}"
    # group: "{{ jupyterhub_service_user }}"
    mode: 0644
  become: true
  tags: "install_jh_config"
  
- name: install jupyter config file
  template:
    src: jupyter_notebook_config.py.j2
    dest: "{{ jupyter_config_dir }}/jupyter_notebook_config.py"
    # owner: "{{ jupyterhub_service_user }}"
    # group: "{{ jupyterhub_service_user }}"
    mode: 0644
  become: true
  tags: "install_jh_config"
