# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Setup jupyterhub conda env and install JupyterHub core components and dependencies

- name: setup conda environment for jupyterhub
  conda:
    name: python
    version: "{{ conda_env_py_version }}"
    environment: "{{ jupyterhub_env_prefix }}"
    state: present
    executable: "{{ conda_prefix }}/bin/conda"
  become: true
  tags: "core"
  
- name: install jupyterhub core components
  conda:
    name: "{{ item }}"
    environment: "{{ jupyterhub_env_prefix }}"
    state: present
    executable: "{{ conda_prefix }}/bin/conda"
  become: true
  with_items:
    - "{{ jupyterhub_pkgs }}"
  tags: "core"
    
- name: install jupyterhub dependencies from pip
  pip:
    executable: "{{ jupyterhub_env_prefix }}/bin/pip"
    name: "{{ item }}"
    extra_args: "--no-cache-dir"
  become: true
  # We need to add conda env bin to PATH as jupyter-server-proxy looks for node and npm
  # while building the package
  environment:
    PATH: "{{ jupyterhub_env_prefix }}/bin:{{ ansible_env.PATH }}"
  with_items:
     - "{{ jupyterhub_deps }}"
  tags: "core"
  
#- name: copy custom packages to remote host
#  copy:
#    src: "{{ lookup('env', 'PWD') }}/packages/{{ item }}"
#    dest: "/tmp"
#    mode: 0770
#  become: true
#  tags: "core"
#  with_items:
#     - "{{ jupyterhub_custom_pkgs }}"
#
#- name: install custom slurm spawner package
#  shell: "source {{ conda_prefix }}/etc/profile.d/conda.sh && conda activate {{ jupyterhub_env_prefix }} && cd /tmp/{{ item }} && pip install --no-cache-dir ."
#  become: true
#  register: install_custom_pkgs
#  changed_when: "'error' not in install_custom_pkgs.stderr"
#  tags: "core"
#  with_items:
#     - "{{ jupyterhub_custom_pkgs }}"
#
#- name: delete package data from /tmp
#  file:
#    path: "/tmp/{{ item }}"
#    state: absent
#  become: yes
#  tags: "core"
#  with_items:
#     - "{{ jupyterhub_custom_pkgs }}"
