# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This tasks generates necessary passwords for monitoring stack

- name: generate passwords for node_exporter and grafana hosts
  set_fact:
    _tmp: "{{ lookup('password', local_passwds_dir + '/' + item + '_node_exporter_passwd length=32 chars=ascii_letters,digits seed=' + item) }}"
  with_items:
    - "{{ groups['node_exporter'] }}"

# See https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md
# bcrypt needs a salt that is atleast 22 bytes long. This is why the following hack
- name: generate password for prometheus
  set_fact:
    _tmp: "{{ lookup('password', local_passwds_dir + '/prometheus_passwd length=32 chars=ascii_letters,digits seed=' + inventory_hostname) | password_hash('bcrypt', lookup('password', local_passwds_dir + '/prometheus_passwd_salt length=21 chars=letters,digits')+'.') }}"
  with_items:
    - "{{ groups['prometheus'] }}"

- name: write hashed prometheus password to file
  copy:
    dest: "{{ local_passwds_dir }}/prometheus_hashed_passwd"
    content: |
      {{ _tmp }}

- name: generate password for grafana
  set_fact:
    _tmp: "{{ lookup('password', local_passwds_dir + '/grafana_passwd length=32 chars=ascii_letters,digits seed=' + item) }}"
  with_items:
    - "{{ groups['grafana'] }}"

- name: generate DB password for grafana
  set_fact:
    _tmp: "{{ lookup('password', local_passwds_dir + '/grafana_db_passwd length=32 chars=ascii_letters,digits seed=' + item) }}"
  with_items:
    - "{{ groups['grafana'] }}"
