# Copyright 2025 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# This task creates various secrets and tokens necessary for JupyterHub
# and monitoring stack

- name: Initialise secrets variable
  ansible.builtin.set_fact:
    __secrets: {}
    __req_tokens: "{{ __req_jp_secrets }}"

- name: Add token to temporary variable
  ansible.builtin.set_fact:
    __secrets: "{{ __secrets | combine({item: lookup('vars', item)}) }}"
  when: lookup('vars', item, default='') | length > 0
  with_items:
    - "{{ __req_tokens }}"

- name: Generate tokens if not already defined in secrets.yml
  ansible.builtin.command: /usr/bin/openssl rand -hex 32
  register: _token_content
  changed_when: _token_content.rc != 0
  when: not lookup('vars', item, default='') | length > 0
  with_items:
    - "{{ __req_tokens }}"

- name: Add generated token to temporary variable
  ansible.builtin.set_fact:
    __secrets: "{{ __secrets | combine({item['item']: item['stdout']}) }}"
  when: item['stdout'] is defined
  with_items:
    - "{{ _token_content['results'] }}"
  loop_control:
    label: Appending token for {{ item['item'] }} in secrets var

- name: Generate JupyterHub crypt tokens
  block:
    - name: Check if JupyterHub crypt key is already defined
      ansible.builtin.set_fact:
        __crypt_tmp: "{{ lookup('vars', 'jupyterhub_crypt_key') }}"
  rescue:
    - name: Generate 5 crypt tokens
      ansible.builtin.command: /usr/bin/openssl rand -hex 32
      with_sequence: count=5
      loop_control:
        loop_var: iter
      register: _crypt_tokens
      changed_when: _crypt_tokens.rc != 0

    - name: Add generated token to temporary variable
      ansible.builtin.set_fact:
        __crypt_tmp: "{{ _crypt_tokens.results | map(attribute='stdout') | join(';') }}"
  always:
    - name: Add JupyterHub crypt token to secrets variable
      ansible.builtin.set_fact:
        __secrets: "{{ __secrets | combine({'jupyterhub_crypt_key': lookup('vars', '__crypt_tmp')}) }}"

- name: Save secrets to file
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/secrets.yml"
    content: |
      ---
      ## This file is managed by Ansible.  ALL CHANGES WILL BE OVERWRITTEN.
      {{ __secrets | to_nice_yaml }}
    mode: "0640"
