# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This tasks generates token necessary for JupyterHub deployment

- name: create folder for placing tokens
  file:
    path: "{{ local_tokens_dir }}"
    state: directory

- name: check if token is already created
  stat:
    path: "{{ local_tokens_dir }}/{{ item }}"
  register: token_path
  
- name: generate token
  shell: "openssl rand -hex 32 > {{ local_tokens_dir }}/{{ item }}"
  args:
    chdir: "{{ local_tokens_dir }}"
    creates: "{{ local_tokens_dir }}/{{ item }}"
  when: not token_path.stat.exists and item != 'crypt_key'
  
- name: generate JupyterHub crypt tokens
  block:
    - name: generate 5 crypt tokens
      command: "openssl rand -hex 32"
      with_sequence: count=5
      loop_control:
        loop_var: iter
      register: crypt_tokens

    - name: save crypt tokens to file
      copy:
        dest: "{{ local_tokens_dir }}/{{ item }}"
        content: "{{ crypt_tokens.results | map(attribute='stdout') | join(';') }}"
  when: not token_path.stat.exists and item == 'crypt_key'
