# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# List of SLURM commands that we want jupyter user to be able to execute with sudo
slurm_cmds:
  - { name: 'SUBMIT_CMD', cmd: 'sbatch' }
  - { name: 'CANCEL_CMD', cmd: 'scancel' }
  - { name: 'SQUEUE_CMD', cmd: 'squeue' }
  
# Path to file in sudoers.d for jupyter service user
sudoers_file: "/etc/sudoers.d/jupyter"

# ---------------------------------------------------
# Jupyterhub conda env configuration
# ---------------------------------------------------

# Jupyterhub environment prefix. Do not need to change normally.
jupyterhub_env_prefix: "{{ jupyter_env_prefix }}/{{ jupyter_env_name }}"

# Path to binaries inside the jupyterhub environment
jupyterhub_env_bin_path: "{{ jupyterhub_env_prefix }}/bin"

# ---------------------------------------------------
# JupyterHub service user
# ---------------------------------------------------

jupyterhub_system_user: "{{ jupyterhub_system_group }}"

# ---------------------------------------------------
# JupyterHub config directories
# ---------------------------------------------------

# Directory where jupyterhub configuration files are placed
jupyterhub_config_dir: "{{ jupyterhub_env_prefix }}/etc/jupyterhub"

# ---------------------------------------------------
# Jupyter config directories
# ---------------------------------------------------

# Directory where jupyter notebook configuration files are placed
jupyter_config_dir: "{{ jupyterhub_env_prefix }}/etc/jupyter"

# Directories to share and templates for notebook servers
jupyter_share_dir: "{{ jupyterhub_env_prefix }}/share/jupyter"
jupyter_templates_dir: "{{ jupyter_config_dir }}/templates"

# ---------------------------------------------------
# IPython config directory
# ---------------------------------------------------

# Directory where IPython configuration files are placed
ipython_config_dir: "{{ jupyterhub_env_prefix }}/etc/ipython"
