# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# We will configure logrotate to rotate logs of nginx and
# jupyterhub
# List of log files to rotate. service_name is the name of
# the service where and log_files are the files to rotate

# Instead, kill sends a specific signal "USR1" which for nginx has a 
# specific meaning and tells the nginx master process to reopen it's log files.
# This effectively means that nginx starts writing to the new log files.
nginx_logfiles:
  - { service_name: "nginx", log_files: ["*.log"], mode: '0644', user: 'nginx', group: 'nginx', postrotate: "kill -USR1 `cat /run/nginx/nginx.pid`" }

jupyterhub_logfiles:
  - { service_name: "jupyterhub", log_files: ["*.log"], mode: '0644', user: 'jupyter', group: 'jupyter', postrotate: "" }
  - { service_name: "jupyterhub-proxy", log_files: ["*.log"], mode: '0644', user: 'jupyter', group: 'jupyter', postrotate: "" }

# grafana writes PID file in that directory. We can get
# this info from grafana-server system service file
grafana_logfiles:
  - { service_name: "grafana", log_files: ["*.log"], mode: '0640', user: 'grafana', group: 'grafana', postrotate: "/bin/kill -HUP `cat /var/run/grafana/grafana-server.pid` > /dev/null 2>/dev/null || true" }
