# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: check prometheus metrics API token exists
  stat:
    path: "{{ jupyterhub_internal_certs_dir }}"
  register: certs_dir
  become: true

- name: create TLS certs for internal communication of JupyterHub
  command: "{{ jupyterhub_env_bin_path }}/jupyterhub --generate-certs -f {{ jupyterhub_config_dir }}/jupyterhub_config.py"
  become: true
  become_user: "{{ jupyterhub_service_user }}"
  when: not certs_dir.stat.exists
  tags: "int-certs"
