# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Tasks to install, configure and setup systemd services for JupyterHub

- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"
    
- import_tasks: install.yml
  tags:
    - install_jupyterhub
    
- import_tasks: directories.yml
    
- import_tasks: tokens.yml
  tags:
    - setup_jupyterhub_tokens
    
- import_tasks: setup_db.yml
  when: use_postgresql_db
  tags:
    - setup_jupyterhub_db
    
- import_tasks: configure.yml
  tags:
    - configure_jupyterhub
    
- import_tasks: services.yml
  tags:
    - configure_jupyterhub_services
