# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Setup PostgresSQL database for jupyterhub

- block:
  - name: check if PostgreSQL database is initialised [CentOS/RedHat]
    stat:
      path: "/var/lib/pgsql/data/pg_hba.conf"
    register: pgsql_stat

  - name: initialise PostgreSQL database [CentOS/RedHat]
    command: "postgresql-setup --initdb"
    when: not pgsql_stat.stat.exists
  
  - name: use md5 as authentication method for databases on localhost [CentOS/RedHat]
    lineinfile:
      dest: "/var/lib/pgsql/data/pg_hba.conf"
      state: present
      regexp: "^{{ item.oldentry }}"
      line: "{{ item.newentry }}"
    
    with_items:
      - { oldentry: "host    all             all             127.0.0.1/32            ident", newentry: "host    all             all             127.0.0.1/32            md5" }
      - { oldentry: "host    all             all             ::1/128                 ident", newentry: "host    all             all             ::1/128                 md5" }
  become: true
  tags: "setup_db"
  when: ansible_os_family == 'RedHat'
  
- block:
  - name: check if PostgreSQL database is initialised [Ubuntu/Debian]
    stat:
      path: "/var/lib/postgresql/data/pg_hba.conf"
    register: pgsql_stat
    tags: "setup_db"

  - name: initialise PostgreSQL database [Ubuntu/Debian]
    command: "/usr/lib/postgresql/13/bin/initdb -D /var/lib/postgresql/data"
    become_user: "postgres"
    when: not pgsql_stat.stat.exists
  
  - name: use md5 as authentication method for databases on localhost [Ubuntu/Debian]
    lineinfile:
      dest: "/var/lib/postgresql/data/pg_hba.conf"
      state: present
      regexp: "^{{ item.oldentry }}"
      line: "{{ item.newentry }}"
    
    with_items:
      - { oldentry: "host    all             all             127.0.0.1/32            trust", newentry: "host    all             all             127.0.0.1/32            md5" }
      - { oldentry: "host    all             all             ::1/128                 trust", newentry: "host    all             all             ::1/128                 md5" }
  become: true
  tags: "setup_db"
  when: ansible_os_family == 'Debian'

# Seems like we have a bug in systemd 239 which comes with CentOS 8
# https://bugs.centos.org/view.php?id=17461
# We need to add this additional conf file to reload daemon post stopping
# the service
- name: add stop.conf to /etc/systemd/system/postgresql.service.d/stop.conf
  block:
   - name: create /etc/systemd/system/postgresql.service.d folder
     file:
       path: "/etc/systemd/system/postgresql.service.d"
       owner: root
       group: root
       mode: '0755'
       state: directory
   - name: create stop.conf file
     copy:
      dest: "/etc/systemd/system/postgresql.service.d/stop.conf"
      owner: root
      group: root
      mode: '0644'
      content: |
        [Service]
        ExecStopPost=+/usr/bin/systemctl daemon-reload
  become: true
  tags: "setup_db"

- name: restart postgresql
  service: 
    name: postgresql 
    state: restarted
  become: true
  tags: "setup_db, molecule-idempotence-notest"

- name: enable postgresql
  service: 
    name: postgresql 
    state: started 
    enabled: yes
  become: true
  tags: "setup_db"
  
- name: create the database for jupyterhub
  postgresql_db: 
    name: "{{ jupyterhub_db_name }}"
    template: "template0"
    state: present
  become: true
  become_user: postgres
  tags: "setup_db"
  
- name: read the db passwd from /srv/jupyterhub folder
  slurp:
    src: "{{ jupyterhub_srv_dir }}/db_passwd"
  become: true
  register: db_passwd
  tags: "setup_db"
  
- name: ensure user has access to the new database
  postgresql_user: 
     db: "{{ jupyterhub_db_name }}"
     name: "{{ jupyterhub_service_user }}"
     password: "{{ db_passwd['content'] | b64decode }}"
     priv: ALL
     state: present
  become: true
  become_user: postgres
  tags: "setup_db"
     
- name: ensure user does not have unnecessary permissions
  postgresql_user: 
     name: "{{ jupyterhub_service_user }}"
     role_attr_flags: NOSUPERUSER,NOCREATEDB
     state: present
  become: true
  become_user: postgres
  tags: "setup_db"
