# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# promtail preflights to give it permissions to read nginx log files

# First we need to create promtail user and group
# We take it directly from original repo
# https://github.com/patrickjahns/ansible-role-promtail/blob/master/tasks/install.yml

- name: create promtail group
  group:
    name: "{{ promtail_system_group }}"
    state: present
    system: True
  when: promtail_system_group != "root"

- name: create the promtail user
  user:
    name: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    groups: "{{ promtail_user_additional_groups }}"
    append: True
    shell: /usr/sbin/nologin
    system: True
    createhome: False
    home: /
  when: promtail_system_user != "root"

- name: grant promtail user to access nginx log dir
  acl:
    path: "/var/log/nginx"
    entity: promtail
    etype: "user"
    permissions: "rx"
    state: present
  become: true

# By this time, this file has not been created
# So will result in error
# - name: grant promtail user to access nginx log dir
#   acl:
#     path: "/var/log/nginx/json_acess.log"
#     entity: promtail
#     etype: "user"
#     permissions: "r"
#     state: present
#   become: true
#   tags: "setup_promtail"
