# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
driver:
  name: docker
lint: |
  yamllint . || exit 0
  ansible-lint -c .ansible-lint --exclude meta | ansible-lint-junit -o ansible-lint.xml || exit 0
platforms:
  - name: slurmcontroller
    image: registry.gitlab.com/idris-cnrs/jupyter/ansible-jupyterhub/docker-slurm-controller-centos8:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    port_bindings:
      - 6817:6817
      - 6818:6818
      - 6819:6819
    hostname: slurmcontroller
    privileged: true
    pre_build_image: true
    
  - name: compute-0
    image: registry.gitlab.com/idris-cnrs/jupyter/ansible-jupyterhub/docker-slurm-compute-centos8:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: compute-0
    privileged: true
    pre_build_image: true
    
  - name: compute-1
    image: registry.gitlab.com/idris-cnrs/jupyter/ansible-jupyterhub/docker-slurm-compute-centos8:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: compute-1
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: hostfile
      host_vars: host_vars/
      group_vars: ../../group_vars/
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    s: true
