# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This playbook prepares Ansible tests.

- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
   - name: configure SLURM
     command: 'sed -i "s/REPLACE_IT/CPUs=$(nproc)/g" /etc/slurm/slurm.conf'
     args:
       executable: /bin/bash
       
   # In default service file of munge they use Type=forking and it has 
   # consequeneces when running docker-in-docker. We got errors from systemd
   # saying that PID file is not owned by root and it is supposed to be not owned
   # by root as process is started as service user munge. Systemd needs PID file as
   # the default Type is forking to be able to stop the process. Here we simplify it
   # by using Type=simple and hence systemd does not need PIDfile anymore and it can
   # stop the process by sending signal to main PID.
   # https://unix.stackexchange.com/questions/534032/systemd-services-fail-with-user-in-service-file
   - name: change Type of systemd file for munge
     copy:
       dest: "/usr/lib/systemd/system/munge.service"
       owner: root
       group: root
       mode: '0644'
       content: |
        [Unit]
        Description=MUNGE authentication service
        Documentation=man:munged(8)
        After=network.target
        After=time-sync.target

        [Service]
        Type=simple
        ExecStart=/usr/sbin/munged
        User=munge
        Group=munge
        Restart=on-abort

        [Install]
        WantedBy=multi-user.target

   - name: enable munge
     service: 
      name: munge 
      state: started 
      enabled: yes
     ignore_errors: yes

   - name: enable slurm controller
     service: 
      name: slurmctld 
      state: started 
      enabled: yes
     when: inventory_hostname in groups['jupyterhub']
     ignore_errors: yes

   - name: start slurm daemon on compute nodes
     shell: slurmd -N $(hostname)
     when: inventory_hostname in groups['compute']
     ignore_errors: yes
