# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This playbook validates the ansible version in environment
  
- name: check SSL files for node_exporter
  block:
   - name: check if SSL key exists
     stat:
       path: "{{ local_path_node_exporter_ssl }}/{{ ssl_key_name_node_exporter }}"
     delegate_to: localhost
     register: key_path

   - name: fail when key file does not exist
     fail:
       msg: "ssl.key cannot be found for node exporter"
     when: not key_path.stat.exists

   - name: check if SSL cert exists
     stat:
       path: "{{ local_path_node_exporter_ssl }}/{{ ssl_cert_name_node_exporter }}"
     delegate_to: localhost
     register: cert_path

   - name: fail when cert file does not exist
     fail:
       msg: "ssl.cert cannot be found for node exporter"
     when: not cert_path.stat.exists
     
   - name: check if SSL key exists
     stat:
       path: "{{ local_path_prometheus_ssl }}/{{ ssl_key_name_prometheus }}"
     delegate_to: localhost
     register: key_path

   - name: fail when key file does not exist
     fail:
       msg: "ssl.key cannot be found for prometheus"
     when: not key_path.stat.exists

   - name: check if SSL cert exists
     stat:
        path: "{{ local_path_prometheus_ssl }}/{{ ssl_cert_name_prometheus }}"
     delegate_to: localhost
     register: cert_path

   - name: fail when cert file does not exist
     fail:
       msg: "ssl.cert cannot be found for prometheus"
     when: not cert_path.stat.exists
     
   - name: check if SSL key exists
     stat:
       path: "{{ local_path_grafana_ssl }}/{{ ssl_key_name_grafana }}"
     delegate_to: localhost
     register: key_path

   - name: fail when key file does not exist
     fail:
       msg: "ssl.key cannot be found for grafana"
     when: not key_path.stat.exists

   - name: check if SSL cert exists
     stat:
       path: "{{ local_path_grafana_ssl }}/{{ ssl_cert_name_grafana }}"
     delegate_to: localhost
    register: cert_path

   - name: fail when cert file does not exist
     fail:
       msg: "ssl.cert cannot be found for grafana"
     when: not cert_path.stat.exists
      
  when: install_mon_stack
  become: true
