# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# Configure loki

- name: make sure /var/log/loki exists
  file:
    path: "/var/log/loki/"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_user }}"
    mode: '0755'
  become: true

- name: create config directories for loki
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: '0755'
  become: true
  with_items:
    - "{{ loki_config_directory }}"
    - "{{ loki_config_store }}"

- name: setup configuration
  template:
    src: "loki.yml.j2"
    dest: "/etc/loki/loki.yml"
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: '0644'
  become: true
  notify:
    - restart systemd loki
