# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# This playbook installs adds conda repository and installs conda using RPMs

- name: add repository configuration file for conda
  yum_repository:
    name: conda
    description: Conda YUM repo
    file: conda.repo
    baseurl: "{{ conda_base_url }}"
    gpgcheck: yes
    gpgkey: "{{ conda_gpgkey }}"
  become: true

- name: install conda
  yum:
    name: conda
    update_cache: yes
    state: present
  become: true
  
- name: add conda config
  copy:
    content: "{{ conda_config | to_yaml }}"
    dest: "{{ conda_prefix }}/.condarc"
  become: true

- name: check for jupyterhub conda environment
  stat:
    path: "{{ conda_prefix }}/envs/{{ conda_env_name }}"
  changed_when: false
  register: conda_env
  become: true

- name: setup conda environment for jupyterhub
  shell:
    cmd: "{{ conda_prefix }}/bin/conda create -p {{ conda_env_prefix }} python={{ conda_env_py_version }} -y"
    executable: "/usr/bin/bash"
  when: not conda_env.stat.exists
  become: true
