# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# This playbook installs common packages used on a UNIX/Linux system

# - name: make sure we have a 'wheel' group
#   group:
#     name: wheel
#     state: present
#   become: true
#
# - name: allow 'wheel' group to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'
#   become: true

- name: add jupyter user
  user:
    name: "{{ jupyter_username }}"
    state: present
    shell: /sbin/nologin
    append: yes
  become: true

- name: add command alias for batchspawner
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^Cmnd_Alias JUPYTER_CMD"
    line: "Cmnd_Alias JUPYTER_CMD = {{ jupyter_env_path }}/bin/batchspawner"
    validate: "visudo -cf %s"
  become: true

- name: add line to give jupyter user permission to use sudo for batchspawner
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ jupyter_username }} ALL=(ALL)"
    line: "{{ jupyter_username }} ALL=(ALL) NOPASSWD:JUPYTER_CMD"
    validate: "visudo -cf %s"
  become: true
